# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods --no-doc # Since Travis is not always on latest version
  - pod repo update
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Amaca.xcworkspace -scheme Amaca-Example -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone XS,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
